### ISSUE TITLE
Bug: Error exception occurs when a user with pending registration tries to log in.

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#465] opened 2022-10-04 19:03 UTC
### PHP Version

7.4

### CodeIgniter4 Version

4.2.6

### Shield Version

develop

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.18

### Did you customize Shield?

No.

### What happened?

I tried to log in without entering the registration confirmation code from the email, and I got the error message: 

```
The user has identities for action, so cannot complete login. If you want to start to login with auth action, use startLogin() instead. Or delete identities for action in database. user_id: 23680
```

### Steps to Reproduce

1. Activate the register action
2. Enable magic link logins
3. Register, but do not get the confirmation code/token from your email
4. Open a new browser, click on magic link to get a one-time-login link
5. Go to your email address and click on the login link

### Expected Output

I expect that the user should be redirected to the auth token confirmation page with a more-descriptive message stating that:

```
You must complete your registration by confirming the tokens sent to your email address.
```

**Comment by datamweb** [comment] 2022-10-04 20:05
Hey @sammyskills ,
Thanks for the report.

This is not a bug and is intentional.
What I understand is that you have a request to add a message to the user.
I agree with clearly displaying the messages to the users and I think it makes the **end users feel good**.

On the other hand, Kenjis is usually concerned about shield security and providing error details.
Therefore, my opinion is **positive by displaying the error message.**
But see what @kenjis says.

**Comment by sammyskills** [comment] 2022-10-04 20:12
Hi @datamweb, 
Thanks for the reply.

One of the reasons why I raised the issue is that in a production environment, the user will be presented with a `whoops` page, which IMO is not ideal for user experience. It is not a problem with the software but from the user, so the user should be made to know that he/she caused the issue.

But just as you said, let see what @kenjis and other team members think about it.

**Comment by kenjis** [comment] 2022-10-04 21:14
This is a bug. Because `LogicException` should not be thrown in production environments.
The logic that uses the Session Auth is incorrect, and should be fixed.
The error message is for devs, not users.

https://github.com/codeigniter4/shield/blob/6c64ec7209fbce08686cc18f0bdd7d732d5d19e9/src/Authentication/Authenticators/Session.php#L695-L703

**Comment by kenjis** [comment] 2022-11-02 06:16
I sent a PR: #503

**Closed** 2022-11-08 01:22 UTC
Labels: bug, enhancement
