### ISSUE TITLE
Bug: magic link - preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated

### ISSUE THREAD

**Issue by tbobker123** [codeigniter4/shield#575] opened 2022-12-29 13:29 UTC
### PHP Version

8.2

### CodeIgniter4 Version

4.2.8

### Shield Version

running composer update and getting latest version does not solve the issue. 

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

5.7.34

### Did you customize Shield?

Nothing has been customised.

### What happened?

I tried to get a magic login link because I forgot the password and when I clicked the send button, an error exception page loads with the error:

`preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated`

### Steps to Reproduce

Click to get a magic link, enter your email address and click send. 

### Expected Output

No error and a magic link to be sent to my email address.

### Anything else?

I suppose its linked to me using the latest PHP version 8.2, but I do not want to modify the core Shield files so if there is anyway to override the logic somewhere else.

**Comment by kenjis** [comment] 2022-12-29 13:35
Duplicate of #289

**Comment by datamweb** [comment] 2022-12-29 13:36
Hi, welcome.
Please read the description of the second (**2**) paragraph .(https://github.com/codeigniter4/shield/blob/develop/docs/install.md#command-setup)

**Closed by datamweb** 2022-12-29 13:36 UTC
Labels: duplicate
